import turtle

j=turtle.Turtle()
j.width(8)
j.color('black','orange')
j.speed(0.5)
j.up()
j.setpos(0,-210)
j.down()
j.begin_fill()
j.circle(200)
j.end_fill()
j.hideturtle()

j=turtle.Turtle()
j.width(3)
j.color('black','gray')
j.speed(0.5)
j.up()
j.setpos(0,-190)
j.down()
j.begin_fill()
j.circle(180)
j.end_fill()
j.hideturtle()

circle=turtle.Turtle()
turtle.tracer(False)
circle.width(5)
circle.speed(0.5)
circle.color('black','darkgreen')
circle.penup()
circle.setpos(50,150)
circle.penup()
circle.begin_fill()
for i in range(62):
    circle.right(35)
    circle.forward(100)
    circle.pendown()
circle.end_fill()
circle.hideturtle()
turtle.tracer(True)
p=turtle.Turtle()
turtle.tracer(False)
p.up()
p.setpos(0,99)
p.down()
p.speed(0.5)
p.width(5)
p.color('lightyellow', 'yellowgreen')
p.begin_fill()
for i in range(13):
    p.circle(56,70)
    p.left(180)
    p.circle(56,70)
p.end_fill()
turtle.tracer(True)
p.hideturtle()

k=turtle.Turtle()
k.up()
k.setpos(0,53.5)
k.down()
k.speed(0.5)
k.width(3)
k.color('navyblue','skyblue')
k.begin_fill()
for i in range(13):
    k.circle(134,70)
    k.left(140)
    k.circle(134,70)
k.end_fill()
k.hideturtle()

flower=turtle.Turtle()
flower.up()
flower.setpos(0,-9)
flower.down()
flower.speed(0.5)
flower.width(3)
flower.color('red','orange')
flower.begin_fill()
for i in range(13):
    flower.circle(53,70)
    flower.left(110)
    flower.circle(53,70)
flower.end_fill()
flower.hideturtle()

