import turtle

t = turtle.Turtle()

window = turtle.Screen()
window.bgcolor("#000000")
theodore=turtle.Turtle()
theodore.color("orange")
theodore.width(3)

theodore.up()
theodore.setposition(-190,50)
theodore.down()

def T(t):
    t.forward(30)
    t.backward(15)
    t.left(90)
    t.backward(60)


def H(h):
    h.up()
    h.right(90)
    h.forward(30)
    h.down()
    h.right(90)
    h.backward(60)
    h.forward(30)
    h.right(90)
    h.backward(30)
    h.left(90)
    h.forward(30)
    h.backward(60)
    
def E(e):
    e.up()
    e.left(90)
    e.forward(15)
    e.down()
    e.forward(30)
    e.left(90)
    e.up()
    e.backward(30)
    e.right(90)
    e.down()
    e.backward(30)
    e.up()
    e.right(90)
    e.backward(30)
    e.down()
    e.forward(60)
    e.left(90)
    e.forward(30)
      
def O(o):
    o.up()
    o.forward(15)
    o.down()
    o.forward(30)
    o.left(90)
    o.forward(60)
    o.left(90)
    o.forward(30)
    o.left(90)
    o.forward(60)

def D(d):
    d.up()
    d.left(90)
    d.forward(45)
    d.left(90)
    d.down()
    d.forward(60)
    d.right(90)
    d.forward(25)
    d.right(50)
    d.forward(10)
    d.right(10)
    d.forward(25)
    d.right(55)
    d.forward(35)
    d.right(65)
    d.forward(30)

def O2(o):
    o.up()
    o.left(180)
    o.forward(55)
    o.left(90)
    o.down()
    o.forward(60)
    o.right(90)
    o.forward(30)
    o.right(90)
    o.forward(60)
    o.right(90)
    o.forward(30)

def R(r):
    r.up()
    r.right(180)
    r.forward(45)
    r.left(90)
    r.down()
    r.forward(60)
    r.right(90)
    r.forward(30)
    r.right(90)
    r.forward(30)
    r.right(90)
    r.forward(30)
    r.left(135)
    r.forward(42)

def E2(e):
    e.up()
    e.left(50)
    e.forward(15)
    e.left(85)
    e.down()
    e.forward(60)
    e.right(90)
    e.forward(30)
    e.up()
    e.right(180)
    e.forward(30)
    e.left(90)
    e.forward(30)
    e.left(90)
    e.down()
    e.forward(30)
    e.up()
    e.right(180)
    e.forward(30)
    e.left(90)
    e.forward(30)
    e.down()
    e.left(90)
    e.forward(30)
    
  
    
#line
    e.up()
    e.left(90)
    e.forward(10)
    e.right(90)
    e.forward(25)
    e.down()
    e.right(90)
    e.forward(30)
    e.right(90)
    e.forward(400)
    e.right(90)
    e.forward(30)
    e.up()
    e.forward(40)
    e.down()
    e.forward(30)
    e.right(90)
    e.forward(400)
    e.right(90)
    e.forward(30)
    
    
    
T(theodore)
H(theodore)
E(theodore)
O(theodore)
D(theodore)
O2(theodore)
R(theodore)
E2(theodore)
